//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFC_MUTE_GUI.rc
//
#define IDD_MUTEMFC2_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_RANDOM_SEED_DLG             129
#define IDD_KEY_LENGTH_DLG              130
#define IDD_GENERATE_KEY_PAIR_DLG       131
#define IDI_MUTE_ICON                   132
#define IDI_NETWORK_ICON                133
#define IDI_DOWNLOAD_ICON               134
#define IDI_PREFERENCES_ICON            135
#define IDI_SEARCH_ICON                 136
#define IDD_TIMED_DLG                   136
#define IDD_MUTE_SEARCH_DLG             137
#define IDD_MUTE_DOWNLOADS_DLG          138
#define IDD_MUTE_UPLOADS_DLG            139
#define IDD_MUTE_CONNECTIONS_DLG        140
#define IDD_MUTE_SETTINGS_DLG           141
#define IDB_DOWN                        142
#define IDB_DOWN2X                      143
#define IDB_UP                          144
#define IDB_UP2X                        145
#define IDB_LED_BITMAPS                 147
#define IDI_UPLOAD_ICON                 149
#define TRAYBUTTON_LUNA_METALLIC_BMP    150
#define TRAYBUTTON_LUNA_BLUE_BMP        151
#define TRAYBUTTON_LUNA_HOMESTEAD_BMP   152
#define IDI_FOLDER_ICON                 153
#define IDI_TRASH_ICON                  156
#define IDI_MESSAGE_ICON                157
#define IDC_HAND_CURSOR                 159
#define IDI_WWW_WEB_ICON                160
#define IDI_FLAG_USA_ICON               161
#define IDD_MUTE_OPTIONS_DLG            164
#define IDD_DIALOG1                     165
#define IDD_MUTE_ABOUT_DLG              165
#define IDD_MUTE_WEB_DLG                166
#define IDD_MUTE_UPLOADS_DLG1           167
#define IDR_SLIDERBAR_GIF               168
#define IDI_MUTE_HELP_ICON              169
#define IDI_EXTERN_LANG_ICON            170
#define IDI_BACK_ICON                   178
#define IDI_NEXT_ICON                   179
#define IDB_ABOUT_LOGO                  180
#define IDB_ABOUT_BACKGROUND            181
#define IDI_PREFERENCES_2_ICON          182
#define IDI_DOWNLOAD2_ICON              183
#define IDI_UPLOAD2_ICON                184
#define IDI_CONNECTIONS_ICON            185
#define IDI_RESTORE_WINDOW_ICON         186
#define IDI_EXIT_MUTE_ICON              187
#define IDI_CANCEL_ICON                 189
#define IDI_CLEAR_ICON                  190
#define IDI_CLEAR_COMPLETE_ICON         191
#define IDI_REMOVE_STALLED_ICON         194
#define IDI_ICON1                       195
#define IDI_DOWNLOAD3_ICON              195
#define IDD_MUTE_SHARED_FILES_DLG       196
#define IDI_SHARED_FILES_ICON           196
#define IDC_SHARED_FILES_LIST           197
#define IDI_REFRESH_ICON                198
#define IDI_ICON2                       200
#define IDI_PRIORITY_ICON               200
#define IDI_ICON3                       202
#define IDI_FLAG_SPAIN_ICON             202
#define IDI_FLAG_DENMARK_ICON           203
#define IDI_FLAG_LITHUANIA_ICON         204
#define IDI_ICON4                       205
#define IDI_FLAG_TURKEY_ICON            205
#define IDI_ICON5                       206
#define IDI_DOWNLOAD5_ICON              206
#define IDI_SEARCH2_ICON                208
#define IDI_STOP_ICON                   209
#define IDI_CLEAR_RESULTS_ICON          210
#define IDI_CLEAR2_ICON                 212
#define IDI_EXPORT_RESULTS_ICON         213
#define IDI_ICON6                       215
#define IDI_DOWNLOAD4_ICON              215
#define IDI_ADD_HOST_ICON               216
#define IDI_SHARED_FILES_EXPORT_ICON    217
#define IDI_ICON8                       219
#define IDI_SHAREDFILES_ICON            220
#define IDI_HOSTLIST_ICON               229
#define IDI_CANCEL_SELECTED_ICON        232
#define IDI_HOSTUPDATE_ICON             233
#define IDI_MYINFO_ICON                 234
#define IDI_CONNECTEDNOTNOT_ICON        235
#define IDI_CONNECTEDLOWLOW_ICON        236
#define IDI_CONNECTEDHIGHHIGH_ICON      237
#define IDC_STATUSBAR                   238
#define IDI_USER_ICON                   238
#define IDI_UP0DOWN0_ICON               239
#define IDI_UP1DOWN0_ICON               240
#define IDI_UP0DOWN1_ICON               241
#define IDI_UP1DOWN1_ICON               242
#define IDC_EDIT_RANDOMNESS             1000
#define IDC_KEY_LENGTH_LIST             1001
#define IDC_STATIC_HOW_LONG             1002
#define IDC_MUTE_MAIN_TAB               1003
#define IDC_SEARCH_STRING_EDIT          1004
#define IDC_SEARCH_BUTTON               1005
#define IDC_PORT_STRING_EDIT            1005
#define IDC_STOP_BUTTON                 1006
#define IDC_BROWSE_BUTTON               1006
#define IDC_BROWSE_SHARED_BUTTON        1006
#define IDC_CONNECTION_LIST             1007
#define IDC_DOWNLOAD_BUTTON             1007
#define IDC_INCOMING_BROWSE_BUTTON      1007
#define IDC_STATIC_STATUS_STR           1008
#define IDC_CLEAR_SEARCH_RESULTS_BUTTON 1008
#define IDC_HASH_BROWSE_BUTTON          1008
#define IDC_SEARCH_LIST                 1009
#define IDC_STATIC_STATUS_STR2          1009
#define IDC_STATIC_IN_OUT_STATS_LABEL   1009
#define IDC_STATIC_IN_OUT_STATS_LABEL_LEFT_1 1009
#define IDC_ADDRESS_STRING_EDIT         1010
#define IDC_EXPORT_SEARCH_RESULTS_BUTTON 1010
#define IDC_ADD_HOST_BUTTON             1011
#define IDC_SEARCH_STRING_EXCLUDE_EDIT  1011
#define IDC_STATIC_PORT                 1012
#define IDC_FILESIZE_EDIT               1012
#define IDC_SEARCHING_TEXT              1013
#define IDC_STATIC_IN_OUT_STATS_LABEL_LEFT_2 1013
#define IDC_SEARCHING_LED               1014
#define IDC_STATIC_IN_OUT_STATS_LABEL_LEFT_3 1014
#define IDC_INBOUND_LIMIT_STRING_EDIT   1015
#define IDC_STATIC_IN_OUT_STATS_LABEL_LEFT_4 1015
#define IDC_STATIC_INBOUND_LABEL        1016
#define IDC_SEARCHFOR_STATIC            1016
#define IDC_STATIC_IN_OUT_STATS_LABEL_LEFT_5 1016
#define IDC_STATIC_INBOUND_UNITS_LABEL  1017
#define IDC_SEARCH_BOOLEAN_STATIC       1017
#define IDC_STATIC_IN_OUT_STATS_LABEL_RIGHT_1 1017
#define IDC_OUTBOUND_LIMIT_STRING_EDIT  1018
#define IDC_EXCLUDE_STATIC              1018
#define IDC_STATIC_IN_OUT_STATS_LABEL_RIGHT_2 1018
#define IDC_STATIC_OUTBOUND_LABEL       1019
#define IDC_FILESIZE_STATIC             1019
#define IDC_STATIC_IN_OUT_STATS_LABEL_RIGHT_3 1019
#define IDC_STATIC_OUTBOUND_UNITS_LABEL 1020
#define IDC_FILESIZE_BOOLEAN_STATIC     1020
#define IDC_STATIC_IN_OUT_STATS_LABEL_RIGHT_4 1020
#define IDC_INITIAL_DL_TO_STRING_EDIT   1021
#define IDC_STATIC_IN_OUT_STATS_LABEL_LEFT_10 1021
#define IDC_STATIC_IN_OUT_STATS_LABEL_RIGHT_5 1021
#define IDC_STATIC_INITIAL_DL_TO_LABEL  1022
#define IDC_STATIC_DL_TO_UNITS_LABEL    1023
#define IDC_MAINTAIN_STRING_EDIT        1024
#define IDC_STATIC_MAINTAIN_LABEL       1025
#define IDC_STATIC_NEIGHBORS_LABEL      1026
#define IDC_ALLOW_STRING_EDIT           1027
#define IDC_STATIC_ALLOW_LABEL          1028
#define IDC_STATIC_NEIGHBORS_LABEL_2    1029
#define IDC_STATIC_SHARE_LABEL          1030
#define IDC_SHARE_STRING_EDIT           1031
#define IDC_SAVE_SETTINGS_BUTTON        1032
#define IDC_UPLOADS_LIST                1033
#define IDC_MAX_UPLOADS_EDIT            1033
#define IDC_CANCEL_BUTTON               1034
#define IDC_STATIC_DELETECANCELED_LABEL 1034
#define IDC_DOWNLOAD_LIST               1035
#define IDC_STATIC_DELETECANCELED_LABEL_EXPLANATION 1035
#define IDC_INCOMING_FOLDER_STRING_EDIT 1035
#define IDC_CLEAR_FAILED_BUTTON         1036
#define IDC_STATIC_MAX_UPLOADS          1036
#define IDC_CLEAR_COMPLETED_BUTTON      1037
#define IDC_COMBO_AND_OR                1037
#define IDC_MAX_UPLOADS_PER_VIP_EDIT    1037
#define IDC_EXPLORE_SHARED_FOLDER       1038
#define IDC_STATIC_RECTANGLE            1038
#define IDC_STATIC_MAX_UPLOADS_PER_VIP  1038
#define IDC_COMBO_FILESIZE              1039
#define IDC_COMBO_DELETE_CANCELED       1039
#define IDC_PURGE_INCOMING_FOLDER       1039
#define IDC_PURGE_HASH_FOLDER           1040
#define IDC_STATIC_DL_GROUP             1040
#define IDC_EXPLORE_INCOMING_FOLDER     1040
#define IDC_STATIC_MSG_LIMITS_GROUP     1041
#define IDC_STATIC_CONNECTIONS_GROUP    1042
#define IDC_STATIC_UL_GROUP             1043
#define IDC_STATIC_MUTE_HOME            1044
#define IDC_STATIC_PLANETPEER_HOME      1045
#define IDC_STATIC_ADDRESS              1045
#define IDC_STATIC_WEBLINK_GROUP        1046
#define IDC_STATIC_KEY_GENERATION_SELECT_SIZE 1046
#define IDC_STATIC_INCOMING_LABEL       1047
#define IDC_STATIC_RANDOMNESS_TEXT      1047
#define IDC_STATIC_PLANETPEER_HOME2     1047
#define IDC_STATIC_MYMUTEINFO_HOME      1047
#define IDC_HASH_FOLDER_STRING_EDIT     1048
#define IDC_STATIC_HASH_LABEL           1049
#define IDC_STATIC_XYBARON_HOME         1050
#define IDC_STATIC_MUTE_SF_MAIN_HOME    1051
#define IDC_COMBO_LANGUAGE              1052
#define IDC_STATIC_LANGUAGE_GROUP       1053
#define IDC_PROGRESS1                   1053
#define IDC_OPTIONS_TREE                1053
#define IDC_STATIC_TIMEDLG_TEXT         1054
#define IDC_CONTAINER_STATIC            1054
#define IDC_STATIC_PORT_GROUP           1054
#define IDC_ABOUT_STATIC                1055
#define IDC_BUTTON_BACK                 1055
#define IDC_ICON_STATIC                 1056
#define IDC_BUTTON_NEXT                 1056
#define IDC_STATIC_SPLITTER             1057
#define IDC_EXPLORER1                   1058
#define IDC_BUTTON_SPLIT                1058
#define IDC_CREDITS_CTRL                1059
#define IDC_REFRESH_BUTTON              1060
#define IDC_EXPORT_SHARED_FILES_LIST_BUTTON 1061
#define IDC_REMOVE_ALL_UPLOAD_BUTTON    1062
#define IDC_UPLOADS_TOTAL_SHOWN_LABEL   1063
#define IDC_UPLOADS_TOTAL_SHOWN_LABEL2  1064
#define IDC_UPLOADS_CHUNKS_UPLOADED_LABEL 1064
#define IDC_CONNECTION_STATUS_LABEL     1064
#define IDC_DOWNLOADS_ICO               1065
#define IDC_DOWNLOADS_STATIC            1066
#define IDC_UPLOADS_ICO                 1067
#define IDC_FILES_ICO                   1068
#define IDC_UPLOADS_STATIC              1068
#define IDC_SHARED_FILES_STATIC         1070
#define IDC_SEARCHLST_ICO               1071
#define IDC_RESULTS_LBL                 1072
#define IDC_STATIC_CON_GRUOP            1074
#define IDC_STATIC_ADDHOST_GROUP        1074
#define IDC_STATIC_UPDATEHOSTS          1075
#define IDC_STATIC_MYINFO               1076
#define IDC_HOSTS_ICO                   1077
#define IDC_HOST_TEXT                   1078
#define IDC_UPDATEHOSTWEBCACHEFROMURL   1084
#define IDC_HOSTWEBCACHEURL             1086
#define IDC_DD2                         1087
#define IDC_ACTIVITY_GIF                1096
#define IDI_FLAG_ITALY_ICON             1161
#define IDI_FLAG_GERMANY_ICON           2161
#define IDI_FLAG_FRANCE_ICON            3161

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        207
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
