
#ifndef _MFC_MUTE_STRING_RESOURCES_H_
#define _MFC_MUTE_STRING_RESOURCES_H_

#define IDS_SEARCH_NORESULT_ENG         1
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_ENG 2
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_ENG 3
#define IDS_KEY_LENGTH_WINDOW_TITLE_ENG 4
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_ENG 5
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_ENG 6
#define IDS_CONNECTIONS_TAB_PORT_TEXT_ENG 7
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_ENG 8
#define IDS_CONNECTIONS_TAB_STARTUP_ENG 9
#define IDS_DLOADS_TAB_PURGE_INCOMING_ENG 10
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_ENG 11
#define IDS_DLOADS_TAB_EXPLORE_SHARED_ENG 12
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_ENG 13
#define IDS_DLOADS_TAB_CLEAR_FAILED_ENG 14
#define IDS_DLOADS_TAB_CANCEL_ENG       15
#define IDS_TAB_TITLE_SEARCH_TEXT_ENG   16
#define IDS_TAB_TITLE_DLOAD_TEXT_ENG    17
#define IDS_TAB_TITLE_ULOAD_TEXT_ENG    18
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_ENG 19
#define IDS_TAB_TITLE_SETTINGS_TEXT_ENG 20
#define IDS_TASK_TRAY_MENU_RESTORE_ENG  21
#define IDS_TASK_TRAY_MENU_QUIT_ENG     22
#define IDS_TRYING_TO_CONNECT_ENG       23
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_ENG 24
#define IDS_BEHIND_FIREWALL_QUESTION_ENG 25
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_ENG 26
#define IDS_TRACE_SAVING_RANDOMNESS_ENG 27
#define IDS_TRACE_STOPPING_MSG_ROUTER_ENG 28
#define IDS_TRACE_ALL_LAYERS_STOPPED_ENG 29
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_ENG 30
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_ENG 31
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_ENG 32
#define IDS_DLOAD_FAILED_ENG            33
#define IDS_DLOAD_NOT_FOUND_ENG         34
#define IDS_DLOAD_FILE_CORRUPTED_ENG    35
#define IDS_DLOAD_CANCELLING_ENG        36
#define IDS_DLOAD_COMPLETE_ENG          37
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_ENG 38
#define IDS_DLOAD_ATTEMPTING_RESUME_ENG 39
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_ENG 40
#define IDS_MUTE_ERROR_CAPTION_ENG      41
#define IDS_PURGE_INCOMING_CAPTION_ENG  42
#define IDS_PURGE_INCOMING_QUESTION_ENG 43
#define IDS_PURGE_INCOMING_CAPTION_ERROR_ENG 44
#define IDS_PURGE_INCOMING_ERROR_MSG_ENG 45
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_ENG 46
#define IDS_512BITS_ENG                 47
#define IDS_1024BITS_ENG                48
#define IDS_1536BITS_ENG                49
#define IDS_2048BITS_ENG                50
#define IDS_4096BITS_ENG                51
#define IDS_KEY_GENERATION_SELECT_SIZE_ENG 52
#define IDS_KEY_GENERATION_DLG_CAPTION_ENG 53
#define IDS_GATHERING_RANDOMNESS_CAPTION_ENG 54
#define IDS_GATHERING_RANDOMNESS_TEXT_ENG 55
#define IDS_KEY_GENERATION_TIME_TEXT_ENG 56
#define IDS_MUTE_CLOSE_MSG_CAPTION_ENG  57
#define IDS_MUTE_CLOSE_MSG_TEXT_ENG     58
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_ENG 59
#define IDS_CONNECTIONS_COLHEADING_PORT_ENG 60
#define IDS_CONNECTIONS_COLHEADING_SENT_ENG 61
#define IDS_CONNECTIONS_COLHEADING_QUEUED_ENG 62
#define IDS_CONNECTIONS_COLHEADING_DROPPED_ENG 63
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_ENG 64
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_ENG 65
#define IDS_SEARCH_SEARCHING_STATUS_ENG 66
#define IDS_SEARCH_IDLE_STATUS_ENG      67
#define IDS_TOOLTIP_PURGE_HASH_FILES_ENG 68
#define IDS_ADDED_TO_DLOADS_PREFIX_ENG  69
#define IDS_EXPORT_SEARCH_DLG_CAPTION_ENG 70
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_ENG 71
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_ENG 72
#define IDS_SEARCH_BOOLEAN_AND_ENG      73
#define IDS_SEARCH_BOOLEAN_OR_ENG       74
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_ENG 75
#define IDS_SEARCH_EXCLUDE_TEXT_ENG     76
#define IDS_SEARCH_FILE_SIZE_LIMITS_ENG 77
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_ENG 78
#define IDS_SEARCH_BOOLEAN_ATLEAST_ENG  79
#define IDS_SEARCH_BOOLEAN_ATMOST_ENG   80
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_ENG 81
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_ENG 82
#define IDS_PURGE_HASHES_MSGBOX_TEXT_ENG 83
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_ENG 84
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_ENG 85
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_ENG 86
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_ENG 87
#define IDS_SEARCH_STOP_BUTTON_TEXT_ENG 88
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_ENG 89
#define IDS_SEARCH_SEARCHFOR_TEXT_ENG   90
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_ENG 91
#define IDS_COL_HEADING_FILENAME_ENG    92
#define IDS_COL_HEADING_FILETYPE_ENG    93
#define IDS_COL_HEADING_SIZE_ENG        94
#define IDS_COL_HEADING_HASH_ENG        95
#define IDS_COL_HEADING_HOST_VIP_ENG    96
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_ENG 97
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_ENG 98
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_ENG 99
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_ENG 100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_ENG 101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_ENG 102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_ENG 103
#define IDS_DLOAD_CANCEL_BUTTON_ENG     104
#define IDS_COL_HEADING_STATUS_ENG      105
#define IDS_COL_HEADING_NUMRESUMES_ENG  106
#define IDS_COL_HEADING_STARTTIME_ENG   107
#define IDS_COL_HEADING_LASTUPDATETIME_ENG 108
#define IDS_COL_HEADING_ROUTEQUALITY_ENG 109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_ENG 110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_ENG 111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_ENG 112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_ENG 113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_ENG 114
#define IDS_DLOAD_CANCELLED_ENG         115
#define IDS_DLOAD_FETCHINGINFO_ENG      116
#define IDS_DLOAD_RESUMING_ENG          117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_ENG 118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_ENG 119
#define IDS_DLOAD_TIME_REMAINING_ENG    120
#define IDS_ULOAD_BTN_REMOVALL_ENG      121
#define IDS_ULOAD_BTN_CANCELCLEAR_ENG   122
#define IDS_ULOAD_LIST_STARTINGUP_ENG   123
#define IDS_ULOAD_STATUS_DONE_ENG       124
#define IDS_ULOAD_STATUS_FAILED_ENG     125
#define IDS_ULOAD_STATUS_STALLED_ENG    126
#define IDS_ULOAD_TIMEREMAINING_ENG     127
#define IDS_COL_HEADING_CHUNKSUPLOADED_ENG 128
#define IDS_COL_HEADING_DESTINATION_VIP_ENG 129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_ENG 130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_ENG 131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_ENG 132
#define IDS_SETTINGS_INBOUND_LIMIT_ENG  133
#define IDS_SETTINGS_OUTBOUND_LIMIT_ENG 134
#define IDS_SETTINGS_MSG_SEC_LIMIT_ENG  135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_ENG 136
#define IDS_SETTINGS_DELETE_CANCELED_DL_ENG 137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_ENG 138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_ENG 139
#define IDS_SETTINGS_CONNECTIONS_GROUP_ENG 140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_ENG 141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_ENG 142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_ENG 143
#define IDS_SETTINGS_MAX_UPLOADS_ENG    144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_ENG 145
#define IDS_BTN_BROWSE_ENG              146
#define IDS_SETTINGS_SHAREFILESFROM_ENG 147
#define IDS_SETTINGS_INCOMING_FOLDER_ENG 148
#define IDS_SETTINGS_HASH_FOLDER_ENG    149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_ENG 150
#define IDS_SETTINGS_WEB_GROUP_ENG      151
#define IDS_SETTINGS_ALLOW_ATMOST_ENG   152
#define IDS_NO_ENG                      153
#define IDS_YES_ENG                     154
#define IDS_SETTINGS_LANGUAGE_GROUP_ENG 155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_ENG 156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_ENG 157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_ENG 158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_ENG 159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_ENG 160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_ENG 161
#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_ENG 162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_ENG 163
#define IDS_DLOAD_QUEUE_ENG             164
#define IDS_DLOAD_QUEUED_ENG            165
#define IDS_DLOAD_QUEUED_SEARCHING_ENG  166
#define IDS_MUTE_HELP_ENG               167
#define IDS_MUTE_ABOUT_ENG              168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_ENG 169
#define IDS_REFRESH_BUTTON_TEXT_ENG     170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_ENG 171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_ENG 172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_ENG 173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_ENG 174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_ENG 175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_ENG 176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_ENG 177
#define IDS_NOTCONNECTED_ENG            178
#define IDS_CONNECTED_ENG               179
#define IDS_UUSERS_ENG                  180
#define IDS_TRAFFIC_TEXT_ENG            181
#define IDS_SEARCH_RESULTS_LBL_ENG      182
#define IDS_UPDOWN_ENG                  183
#define IDS_MUTENET_ENG                 184
















































#define IDS_SEARCH_NORESULT_ITA         1001

#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_ITA 1002

#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_ITA 1003

#define IDS_KEY_LENGTH_WINDOW_TITLE_ITA 1004


#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_ITA 1005



#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_ITA 1006



#define IDS_CONNECTIONS_TAB_PORT_TEXT_ITA 1007



#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_ITA 1008

#define IDS_CONNECTIONS_TAB_STARTUP_ITA 1009





#define IDS_DLOADS_TAB_PURGE_INCOMING_ITA 1010


#define IDS_DLOADS_TAB_EXPLORE_INCOMING_ITA 1011


#define IDS_DLOADS_TAB_EXPLORE_SHARED_ITA 1012

#define IDS_DLOADS_TAB_CLEAR_COMPLETE_ITA 1013


#define IDS_DLOADS_TAB_CLEAR_FAILED_ITA 1014


#define IDS_DLOADS_TAB_CANCEL_ITA       1015



#define IDS_TAB_TITLE_SEARCH_TEXT_ITA   1016



#define IDS_TAB_TITLE_DLOAD_TEXT_ITA    1017



#define IDS_TAB_TITLE_ULOAD_TEXT_ITA    1018



#define IDS_TAB_TITLE_CONNECTIONS_TEXT_ITA 1019



#define IDS_TAB_TITLE_SETTINGS_TEXT_ITA 1020


#define IDS_TASK_TRAY_MENU_RESTORE_ITA  1021



#define IDS_TASK_TRAY_MENU_QUIT_ITA     1022

#define IDS_TRYING_TO_CONNECT_ITA       1023

#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_ITA 1024

#define IDS_BEHIND_FIREWALL_QUESTION_ITA 1025

#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_ITA 1026

#define IDS_TRACE_SAVING_RANDOMNESS_ITA 1027

#define IDS_TRACE_STOPPING_MSG_ROUTER_ITA 1028

#define IDS_TRACE_ALL_LAYERS_STOPPED_ITA 1029

#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_ITA 1030

#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_ITA 1031

#define IDS_TOOLTIP_PURGE_INCOMING_FILES_ITA 1032


#define IDS_DLOAD_FAILED_ITA            1033


#define IDS_DLOAD_NOT_FOUND_ITA         1034



#define IDS_DLOAD_FILE_CORRUPTED_ITA    1035


#define IDS_DLOAD_CANCELLING_ITA        1036



#define IDS_DLOAD_COMPLETE_ITA          1037



#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_ITA 1038



#define IDS_DLOAD_ATTEMPTING_RESUME_ITA 1039



#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_ITA 1040

#define IDS_MUTE_ERROR_CAPTION_ITA      1041

#define IDS_PURGE_INCOMING_CAPTION_ITA  1042

#define IDS_PURGE_INCOMING_QUESTION_ITA 1043

#define IDS_PURGE_INCOMING_CAPTION_ERROR_ITA 1044


#define IDS_PURGE_INCOMING_ERROR_MSG_ITA 1045


#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_ITA 1046


#define IDS_512BITS_ITA                 1047

#define IDS_1024BITS_ITA                1048

#define IDS_1536BITS_ITA                1049

#define IDS_2048BITS_ITA                1050

#define IDS_4096BITS_ITA                1051
#define IDS_KEY_GENERATION_SELECT_SIZE_ITA 1052

#define IDS_KEY_GENERATION_DLG_CAPTION_ITA 1053



#define IDS_GATHERING_RANDOMNESS_CAPTION_ITA 1054



#define IDS_GATHERING_RANDOMNESS_TEXT_ITA 1055


#define IDS_KEY_GENERATION_TIME_TEXT_ITA 1056


#define IDS_MUTE_CLOSE_MSG_CAPTION_ITA  1057

#define IDS_MUTE_CLOSE_MSG_TEXT_ITA     1058


#define IDS_CONNECTIONS_COLHEADING_ADDRESS_ITA 1059

#define IDS_CONNECTIONS_COLHEADING_PORT_ITA 1060

#define IDS_CONNECTIONS_COLHEADING_SENT_ITA 1061

#define IDS_CONNECTIONS_COLHEADING_QUEUED_ITA 1062

#define IDS_CONNECTIONS_COLHEADING_DROPPED_ITA 1063

#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_ITA 1064



#define IDS_ADDHOST_ERROR_MSGBOX_MSG_ITA 1065

#define IDS_SEARCH_SEARCHING_STATUS_ITA 1066

#define IDS_SEARCH_IDLE_STATUS_ITA      1067

#define IDS_TOOLTIP_PURGE_HASH_FILES_ITA 1068


#define IDS_ADDED_TO_DLOADS_PREFIX_ITA  1069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_ITA 1070

#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_ITA 1071

#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_ITA 1072

#define IDS_SEARCH_BOOLEAN_AND_ITA      1073
#define IDS_SEARCH_BOOLEAN_OR_ITA       1074


#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_ITA 1075

#define IDS_SEARCH_EXCLUDE_TEXT_ITA     1076

#define IDS_SEARCH_FILE_SIZE_LIMITS_ITA 1077

#define IDS_SEARCH_FILE_SIZE_BOOLEAN_ITA 1078

#define IDS_SEARCH_BOOLEAN_ATLEAST_ITA  1079
#define IDS_SEARCH_BOOLEAN_ATMOST_ITA   1080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_ITA 1081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_ITA 1082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_ITA 1083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_ITA 1084

#define IDS_SEARCH_DLOAD_BUTTON_TEXT_ITA 1085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_ITA 1086

#define IDS_SEARCH_SEARCH_BUTTON_TEXT_ITA 1087

#define IDS_SEARCH_STOP_BUTTON_TEXT_ITA 1088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_ITA 1089
#define IDS_SEARCH_SEARCHFOR_TEXT_ITA   1090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_ITA 1091
#define IDS_COL_HEADING_FILENAME_ITA    1092
#define IDS_COL_HEADING_FILETYPE_ITA    1093
#define IDS_COL_HEADING_SIZE_ITA        1094
#define IDS_COL_HEADING_HASH_ITA        1095
#define IDS_COL_HEADING_HOST_VIP_ITA    1096

#define IDS_SEARCH_RT_CLK_MENU_CAPTION_ITA 1097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_ITA 1098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_ITA 1099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_ITA 1100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_ITA 1101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_ITA 1102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_ITA 1103
#define IDS_DLOAD_CANCEL_BUTTON_ITA     1104
#define IDS_COL_HEADING_STATUS_ITA      1105
#define IDS_COL_HEADING_NUMRESUMES_ITA  1106
#define IDS_COL_HEADING_STARTTIME_ITA   1107
#define IDS_COL_HEADING_LASTUPDATETIME_ITA 1108
#define IDS_COL_HEADING_ROUTEQUALITY_ITA 1109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_ITA 1110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_ITA 1111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_ITA 1112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_ITA 1113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_ITA 1114
#define IDS_DLOAD_CANCELLED_ITA         1115
#define IDS_DLOAD_FETCHINGINFO_ITA      1116
#define IDS_DLOAD_RESUMING_ITA          1117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_ITA 1118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_ITA 1119
#define IDS_DLOAD_TIME_REMAINING_ITA    1120
#define IDS_ULOAD_BTN_REMOVALL_ITA      1121
#define IDS_ULOAD_BTN_CANCELCLEAR_ITA   1122
#define IDS_ULOAD_LIST_STARTINGUP_ITA   1123
#define IDS_ULOAD_STATUS_DONE_ITA       1124
#define IDS_ULOAD_STATUS_FAILED_ITA     1125
#define IDS_ULOAD_STATUS_STALLED_ITA    1126
#define IDS_ULOAD_TIMEREMAINING_ITA     1127
#define IDS_COL_HEADING_CHUNKSUPLOADED_ITA 1128
#define IDS_COL_HEADING_DESTINATION_VIP_ITA 1129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_ITA 1130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_ITA 1131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_ITA 1132
#define IDS_SETTINGS_INBOUND_LIMIT_ITA  1133
#define IDS_SETTINGS_OUTBOUND_LIMIT_ITA 1134
#define IDS_SETTINGS_MSG_SEC_LIMIT_ITA  1135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_ITA 1136
#define IDS_SETTINGS_DELETE_CANCELED_DL_ITA 1137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_ITA 1138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_ITA 1139
#define IDS_SETTINGS_CONNECTIONS_GROUP_ITA 1140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_ITA 1141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_ITA 1142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_ITA 1143
#define IDS_SETTINGS_MAX_UPLOADS_ITA    1144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_ITA 1145
#define IDS_BTN_BROWSE_ITA              1146
#define IDS_SETTINGS_SHAREFILESFROM_ITA 1147
#define IDS_SETTINGS_INCOMING_FOLDER_ITA 1148
#define IDS_SETTINGS_HASH_FOLDER_ITA    1149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_ITA 1150
#define IDS_SETTINGS_WEB_GROUP_ITA      1151
#define IDS_SETTINGS_ALLOW_ATMOST_ITA   1152
#define IDS_NO_ITA                      1153
#define IDS_YES_ITA                     1154
#define IDS_SETTINGS_LANGUAGE_GROUP_ITA 1155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_ITA 1156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_ITA 1157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_ITA 1158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_ITA 1159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_ITA 1160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_ITA 1161

#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_ITA 1162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_ITA 1163
#define IDS_DLOAD_QUEUE_ITA             1164
#define IDS_DLOAD_QUEUED_ITA            1165
#define IDS_DLOAD_QUEUED_SEARCHING_ITA  1166
#define IDS_MUTE_HELP_ITA               1167
#define IDS_MUTE_ABOUT_ITA              1168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_ITA 1169
#define IDS_REFRESH_BUTTON_TEXT_ITA     1170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_ITA 1171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_ITA 1172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_ITA 1173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_ITA 1174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_ITA 1175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_ITA 1176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_ITA 1177
#define IDS_NOTCONNECTED_ITA            1178
#define IDS_CONNECTED_ITA               1179
#define IDS_UUSERS_ITA                  1180
#define IDS_TRAFFIC_TEXT_ITA            1181
#define IDS_SEARCH_RESULTS_LBL_ITA      1182
#define IDS_UPDOWN_ITA                  1183
#define IDS_MUTENET_ITA                 1184
#define IDS_SEARCH_NORESULT_GER         2001
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_GER 2002
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_GER 2003
#define IDS_KEY_LENGTH_WINDOW_TITLE_GER 2004
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_GER 2005
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_GER 2006
#define IDS_CONNECTIONS_TAB_PORT_TEXT_GER 2007
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_GER 2008
#define IDS_CONNECTIONS_TAB_STARTUP_GER 2009
#define IDS_DLOADS_TAB_PURGE_INCOMING_GER 2010
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_GER 2011
#define IDS_DLOADS_TAB_EXPLORE_SHARED_GER 2012
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_GER 2013
#define IDS_DLOADS_TAB_CLEAR_FAILED_GER 2014
#define IDS_DLOADS_TAB_CANCEL_GER       2015
#define IDS_TAB_TITLE_SEARCH_TEXT_GER   2016
#define IDS_TAB_TITLE_DLOAD_TEXT_GER    2017
#define IDS_TAB_TITLE_ULOAD_TEXT_GER    2018
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_GER 2019
#define IDS_TAB_TITLE_SETTINGS_TEXT_GER 2020
#define IDS_TASK_TRAY_MENU_RESTORE_GER  2021
#define IDS_TASK_TRAY_MENU_QUIT_GER     2022
#define IDS_TRYING_TO_CONNECT_GER       2023
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_GER 2024
#define IDS_BEHIND_FIREWALL_QUESTION_GER 2025
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_GER 2026
#define IDS_TRACE_SAVING_RANDOMNESS_GER 2027
#define IDS_TRACE_STOPPING_MSG_ROUTER_GER 2028
#define IDS_TRACE_ALL_LAYERS_STOPPED_GER 2029
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_GER 2030
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_GER 2031
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_GER 2032
#define IDS_DLOAD_FAILED_GER            2033
#define IDS_DLOAD_NOT_FOUND_GER         2034
#define IDS_DLOAD_FILE_CORRUPTED_GER    2035
#define IDS_DLOAD_CANCELLING_GER        2036
#define IDS_DLOAD_COMPLETE_GER          2037
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_GER 2038
#define IDS_DLOAD_ATTEMPTING_RESUME_GER 2039
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_GER 2040
#define IDS_MUTE_ERROR_CAPTION_GER      2041
#define IDS_PURGE_INCOMING_CAPTION_GER  2042
#define IDS_PURGE_INCOMING_QUESTION_GER 2043
#define IDS_PURGE_INCOMING_CAPTION_ERROR_GER 2044
#define IDS_PURGE_INCOMING_ERROR_MSG_GER 2045
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_GER 2046
#define IDS_512BITS_GER                 2047
#define IDS_1024BITS_GER                2048
#define IDS_1536BITS_GER                2049
#define IDS_2048BITS_GER                2050
#define IDS_4096BITS_GER                2051
#define IDS_KEY_GENERATION_SELECT_SIZE_GER 2052
#define IDS_KEY_GENERATION_DLG_CAPTION_GER 2053
#define IDS_GATHERING_RANDOMNESS_CAPTION_GER 2054
#define IDS_GATHERING_RANDOMNESS_TEXT_GER 2055
#define IDS_KEY_GENERATION_TIME_TEXT_GER 2056
#define IDS_MUTE_CLOSE_MSG_CAPTION_GER  2057
#define IDS_MUTE_CLOSE_MSG_TEXT_GER     2058
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_GER 2059
#define IDS_CONNECTIONS_COLHEADING_PORT_GER 2060
#define IDS_CONNECTIONS_COLHEADING_SENT_GER 2061
#define IDS_CONNECTIONS_COLHEADING_QUEUED_GER 2062
#define IDS_CONNECTIONS_COLHEADING_DROPPED_GER 2063
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_GER 2064
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_GER 2065
#define IDS_SEARCH_SEARCHING_STATUS_GER 2066
#define IDS_SEARCH_IDLE_STATUS_GER      2067
#define IDS_TOOLTIP_PURGE_HASH_FILES_GER 2068
#define IDS_ADDED_TO_DLOADS_PREFIX_GER  2069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_GER 2070
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_GER 2071
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_GER 2072
#define IDS_SEARCH_BOOLEAN_AND_GER      2073
#define IDS_SEARCH_BOOLEAN_OR_GER       2074
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_GER 2075
#define IDS_SEARCH_EXCLUDE_TEXT_GER     2076
#define IDS_SEARCH_FILE_SIZE_LIMITS_GER 2077
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_GER 2078
#define IDS_SEARCH_BOOLEAN_ATLEAST_GER  2079
#define IDS_SEARCH_BOOLEAN_ATMOST_GER   2080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_GER 2081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_GER 2082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_GER 2083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_GER 2084
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_GER 2085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_GER 2086
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_GER 2087
#define IDS_SEARCH_STOP_BUTTON_TEXT_GER 2088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_GER 2089
#define IDS_SEARCH_SEARCHFOR_TEXT_GER   2090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_GER 2091
#define IDS_COL_HEADING_FILENAME_GER    2092
#define IDS_COL_HEADING_FILETYPE_GER    2093
#define IDS_COL_HEADING_SIZE_GER        2094
#define IDS_COL_HEADING_HASH_GER        2095
#define IDS_COL_HEADING_HOST_VIP_GER    2096
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_GER 2097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_GER 2098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_GER 2099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_GER 2100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_GER 2101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_GER 2102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_GER 2103
#define IDS_DLOAD_CANCEL_BUTTON_GER     2104
#define IDS_COL_HEADING_STATUS_GER      2105
#define IDS_COL_HEADING_NUMRESUMES_GER  2106
#define IDS_COL_HEADING_STARTTIME_GER   2107
#define IDS_COL_HEADING_LASTUPDATETIME_GER 2108
#define IDS_COL_HEADING_ROUTEQUALITY_GER 2109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_GER 2110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_GER 2111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_GER 2112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_GER 2113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_GER 2114
#define IDS_DLOAD_CANCELLED_GER         2115
#define IDS_DLOAD_FETCHINGINFO_GER      2116
#define IDS_DLOAD_RESUMING_GER          2117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_GER 2118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_GER 2119
#define IDS_DLOAD_TIME_REMAINING_GER    2120
#define IDS_ULOAD_BTN_REMOVALL_GER      2121
#define IDS_ULOAD_BTN_CANCELCLEAR_GER   2122
#define IDS_ULOAD_LIST_STARTINGUP_GER   2123
#define IDS_ULOAD_STATUS_DONE_GER       2124
#define IDS_ULOAD_STATUS_FAILED_GER     2125
#define IDS_ULOAD_STATUS_STALLED_GER    2126
#define IDS_ULOAD_TIMEREMAINING_GER     2127
#define IDS_COL_HEADING_CHUNKSUPLOADED_GER 2128
#define IDS_COL_HEADING_DESTINATION_VIP_GER 2129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_GER 2130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_GER 2131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_GER 2132
#define IDS_SETTINGS_INBOUND_LIMIT_GER  2133
#define IDS_SETTINGS_OUTBOUND_LIMIT_GER 2134
#define IDS_SETTINGS_MSG_SEC_LIMIT_GER  2135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_GER 2136
#define IDS_SETTINGS_DELETE_CANCELED_DL_GER 2137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_GER 2138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_GER 2139
#define IDS_SETTINGS_CONNECTIONS_GROUP_GER 2140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_GER 2141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_GER 2142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_GER 2143
#define IDS_SETTINGS_MAX_UPLOADS_GER    2144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_GER 2145
#define IDS_BTN_BROWSE_GER              2146
#define IDS_SETTINGS_SHAREFILESFROM_GER 2147
#define IDS_SETTINGS_INCOMING_FOLDER_GER 2148
#define IDS_SETTINGS_HASH_FOLDER_GER    2149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_GER 2150
#define IDS_SETTINGS_WEB_GROUP_GER      2151
#define IDS_SETTINGS_ALLOW_ATMOST_GER   2152
#define IDS_NO_GER                      2153
#define IDS_YES_GER                     2154
#define IDS_SETTINGS_LANGUAGE_GROUP_GER 2155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_GER 2156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_GER 2157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_GER 2158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_GER 2159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_GER 2160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_GER 2161

#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_GER 2162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_GER 2163
#define IDS_DLOAD_QUEUE_GER             2164
#define IDS_DLOAD_QUEUED_GER            2165
#define IDS_DLOAD_QUEUED_SEARCHING_GER  2166
#define IDS_MUTE_HELP_GER               2167
#define IDS_MUTE_ABOUT_GER              2168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_GER 2169
#define IDS_REFRESH_BUTTON_TEXT_GER     2170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_GER 2171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_GER 2172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_GER 2173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_GER 2174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_GER 2175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_GER 2176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_GER 2177
#define IDS_NOTCONNECTED_GER            2178
#define IDS_CONNECTED_GER               2179
#define IDS_UUSERS_GER                  2180
#define IDS_TRAFFIC_TEXT_GER            2181
#define IDS_SEARCH_RESULTS_LBL_GER      2182
#define IDS_UPDOWN_GER                  2183
#define IDS_MUTENET_GER                 2184
#define IDS_SEARCH_NORESULT_FR          3001
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_FR 3002
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_FR 3003
#define IDS_KEY_LENGTH_WINDOW_TITLE_FR  3004
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_FR 3005
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_FR 3006
#define IDS_CONNECTIONS_TAB_PORT_TEXT_FR 3007
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_FR 3008
#define IDS_CONNECTIONS_TAB_STARTUP_FR  3009
#define IDS_DLOADS_TAB_PURGE_INCOMING_FR 3010
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_FR 3011
#define IDS_DLOADS_TAB_EXPLORE_SHARED_FR 3012
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_FR 3013
#define IDS_DLOADS_TAB_CLEAR_FAILED_FR  3014
#define IDS_DLOADS_TAB_CANCEL_FR        3015
#define IDS_TAB_TITLE_SEARCH_TEXT_FR    3016
#define IDS_TAB_TITLE_DLOAD_TEXT_FR     3017
#define IDS_TAB_TITLE_ULOAD_TEXT_FR     3018
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_FR 3019
#define IDS_TAB_TITLE_SETTINGS_TEXT_FR  3020
#define IDS_TASK_TRAY_MENU_RESTORE_FR   3021
#define IDS_TASK_TRAY_MENU_QUIT_FR      3022
#define IDS_TRYING_TO_CONNECT_FR        3023
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_FR 3024
#define IDS_BEHIND_FIREWALL_QUESTION_FR 3025
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_FR 3026
#define IDS_TRACE_SAVING_RANDOMNESS_FR  3027
#define IDS_TRACE_STOPPING_MSG_ROUTER_FR 3028
#define IDS_TRACE_ALL_LAYERS_STOPPED_FR 3029
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_FR 3030
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_FR 3031
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_FR 3032
#define IDS_DLOAD_FAILED_FR             3033
#define IDS_DLOAD_NOT_FOUND_FR          3034
#define IDS_DLOAD_FILE_CORRUPTED_FR     3035
#define IDS_DLOAD_CANCELLING_FR         3036
#define IDS_DLOAD_COMPLETE_FR           3037
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_FR 3038
#define IDS_DLOAD_ATTEMPTING_RESUME_FR  3039
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_FR 3040
#define IDS_MUTE_ERROR_CAPTION_FR       3041
#define IDS_PURGE_INCOMING_CAPTION_FR   3042
#define IDS_PURGE_INCOMING_QUESTION_FR  3043
#define IDS_PURGE_INCOMING_CAPTION_ERROR_FR 3044
#define IDS_PURGE_INCOMING_ERROR_MSG_FR 3045
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_FR 3046
#define IDS_512BITS_FR                  3047
#define IDS_1024BITS_FR                 3048
#define IDS_1536BITS_FR                 3049
#define IDS_2048BITS_FR                 3050
#define IDS_4096BITS_FR                 3051
#define IDS_KEY_GENERATION_SELECT_SIZE_FR 3052
#define IDS_KEY_GENERATION_DLG_CAPTION_FR 3053
#define IDS_GATHERING_RANDOMNESS_CAPTION_FR 3054
#define IDS_GATHERING_RANDOMNESS_TEXT_FR 3055
#define IDS_KEY_GENERATION_TIME_TEXT_FR 3056
#define IDS_MUTE_CLOSE_MSG_CAPTION_FR   3057
#define IDS_MUTE_CLOSE_MSG_TEXT_FR      3058
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_FR 3059
#define IDS_CONNECTIONS_COLHEADING_PORT_FR 3060
#define IDS_CONNECTIONS_COLHEADING_SENT_FR 3061
#define IDS_CONNECTIONS_COLHEADING_QUEUED_FR 3062
#define IDS_CONNECTIONS_COLHEADING_DROPPED_FR 3063
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_FR 3064
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_FR 3065
#define IDS_SEARCH_SEARCHING_STATUS_FR  3066
#define IDS_SEARCH_IDLE_STATUS_FR       3067
#define IDS_TOOLTIP_PURGE_HASH_FILES_FR 3068
#define IDS_ADDED_TO_DLOADS_PREFIX_FR   3069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_FR 3070
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_FR 3071
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_FR 3072
#define IDS_SEARCH_BOOLEAN_AND_FR       3073
#define IDS_SEARCH_BOOLEAN_OR_FR        3074
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_FR 3075
#define IDS_SEARCH_EXCLUDE_TEXT_FR      3076
#define IDS_SEARCH_FILE_SIZE_LIMITS_FR  3077
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_FR 3078
#define IDS_SEARCH_BOOLEAN_ATLEAST_FR   3079
#define IDS_SEARCH_BOOLEAN_ATMOST_FR    3080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_FR 3081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_FR 3082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_FR 3083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_FR 3084
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_FR 3085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_FR 3086
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_FR 3087
#define IDS_SEARCH_STOP_BUTTON_TEXT_FR  3088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_FR 3089
#define IDS_SEARCH_SEARCHFOR_TEXT_FR    3090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_FR 3091
#define IDS_COL_HEADING_FILENAME_FR     3092
#define IDS_COL_HEADING_FILETYPE_FR     3093
#define IDS_COL_HEADING_SIZE_FR         3094
#define IDS_COL_HEADING_HASH_FR         3095
#define IDS_COL_HEADING_HOST_VIP_FR     3096
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_FR 3097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_FR 3098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_FR 3099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_FR 3100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_FR 3101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_FR 3102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_FR 3103
#define IDS_DLOAD_CANCEL_BUTTON_FR      3104
#define IDS_COL_HEADING_STATUS_FR       3105
#define IDS_COL_HEADING_NUMRESUMES_FR   3106
#define IDS_COL_HEADING_STARTTIME_FR    3107
#define IDS_COL_HEADING_LASTUPDATETIME_FR 3108
#define IDS_COL_HEADING_ROUTEQUALITY_FR 3109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_FR 3110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_FR 3111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_FR  3112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_FR 3113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_FR 3114
#define IDS_DLOAD_CANCELLED_FR          3115
#define IDS_DLOAD_FETCHINGINFO_FR       3116
#define IDS_DLOAD_RESUMING_FR           3117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_FR 3118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_FR 3119
#define IDS_DLOAD_TIME_REMAINING_FR     3120
#define IDS_ULOAD_BTN_REMOVALL_FR       3121
#define IDS_ULOAD_BTN_CANCELCLEAR_FR    3122
#define IDS_ULOAD_LIST_STARTINGUP_FR    3123
#define IDS_ULOAD_STATUS_DONE_FR        3124
#define IDS_ULOAD_STATUS_FAILED_FR      3125
#define IDS_ULOAD_STATUS_STALLED_FR     3126
#define IDS_ULOAD_TIMEREMAINING_FR      3127
#define IDS_COL_HEADING_CHUNKSUPLOADED_FR 3128
#define IDS_COL_HEADING_DESTINATION_VIP_FR 3129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_FR 3130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_FR 3131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_FR 3132
#define IDS_SETTINGS_INBOUND_LIMIT_FR   3133
#define IDS_SETTINGS_OUTBOUND_LIMIT_FR  3134
#define IDS_SETTINGS_MSG_SEC_LIMIT_FR   3135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_FR 3136
#define IDS_SETTINGS_DELETE_CANCELED_DL_FR 3137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_FR 3138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_FR 3139
#define IDS_SETTINGS_CONNECTIONS_GROUP_FR 3140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_FR 3141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_FR 3142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_FR 3143
#define IDS_SETTINGS_MAX_UPLOADS_FR     3144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_FR 3145
#define IDS_BTN_BROWSE_FR               3146
#define IDS_SETTINGS_SHAREFILESFROM_FR  3147
#define IDS_SETTINGS_INCOMING_FOLDER_FR 3148
#define IDS_SETTINGS_HASH_FOLDER_FR     3149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_FR 3150
#define IDS_SETTINGS_WEB_GROUP_FR       3151
#define IDS_SETTINGS_ALLOW_ATMOST_FR    3152
#define IDS_NO_FR                       3153
#define IDS_YES_FR                      3154
#define IDS_SETTINGS_LANGUAGE_GROUP_FR  3155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_FR 3156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_FR 3157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_FR 3158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_FR 3159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_FR 3160

#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_FR 3161
#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_FR 3162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_FR 3163
#define IDS_DLOAD_QUEUE_FR              3164
#define IDS_DLOAD_QUEUED_FR             3165
#define IDS_DLOAD_QUEUED_SEARCHING_FR   3166
#define IDS_MUTE_HELP_FR                3167
#define IDS_MUTE_ABOUT_FR               3168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_FR 3169
#define IDS_REFRESH_BUTTON_TEXT_FR      3170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_FR 3171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_FR 3172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_FR 3173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_FR 3174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_FR 3175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_FR 3176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_FR 3177
#define IDS_NOTCONNECTED_FR             3178
#define IDS_CONNECTED_FR                3179
#define IDS_UUSERS_FR                   3180
#define IDS_TRAFFIC_TEXT_FR             3181
#define IDS_SEARCH_RESULTS_LBL_FR       3182
#define IDS_UPDOWN_FR                   3183
#define IDS_MUTENET_FR                  3184
#define IDS_SEARCH_NORESULT_SPA         4001
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_SPA 4002
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_SPA 4003
#define IDS_KEY_LENGTH_WINDOW_TITLE_SPA 4004
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_SPA 4005
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_SPA 4006
#define IDS_CONNECTIONS_TAB_PORT_TEXT_SPA 4007
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_SPA 4008
#define IDS_CONNECTIONS_TAB_STARTUP_SPA 4009
#define IDS_DLOADS_TAB_PURGE_INCOMING_SPA 4010
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_SPA 4011
#define IDS_DLOADS_TAB_EXPLORE_SHARED_SPA 4012
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_SPA 4013
#define IDS_DLOADS_TAB_CLEAR_FAILED_SPA 4014
#define IDS_DLOADS_TAB_CANCEL_SPA       4015
#define IDS_TAB_TITLE_SEARCH_TEXT_SPA   4016
#define IDS_TAB_TITLE_DLOAD_TEXT_SPA    4017
#define IDS_TAB_TITLE_ULOAD_TEXT_SPA    4018
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_SPA 4019
#define IDS_TAB_TITLE_SETTINGS_TEXT_SPA 4020
#define IDS_TASK_TRAY_MENU_RESTORE_SPA  4021
#define IDS_TASK_TRAY_MENU_QUIT_SPA     4022
#define IDS_TRYING_TO_CONNECT_SPA       4023
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_SPA 4024
#define IDS_BEHIND_FIREWALL_QUESTION_SPA 4025
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_SPA 4026
#define IDS_TRACE_SAVING_RANDOMNESS_SPA 4027
#define IDS_TRACE_STOPPING_MSG_ROUTER_SPA 4028
#define IDS_TRACE_ALL_LAYERS_STOPPED_SPA 4029
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_SPA 4030
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_SPA 4031
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_SPA 4032
#define IDS_DLOAD_FAILED_SPA            4033
#define IDS_DLOAD_NOT_FOUND_SPA         4034
#define IDS_DLOAD_FILE_CORRUPTED_SPA    4035
#define IDS_DLOAD_CANCELLING_SPA        4036
#define IDS_DLOAD_COMPLETE_SPA          4037
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_SPA 4038
#define IDS_DLOAD_ATTEMPTING_RESUME_SPA 4039
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_SPA 4040
#define IDS_MUTE_ERROR_CAPTION_SPA      4041
#define IDS_PURGE_INCOMING_CAPTION_SPA  4042
#define IDS_PURGE_INCOMING_QUESTION_SPA 4043
#define IDS_PURGE_INCOMING_CAPTION_ERROR_SPA 4044
#define IDS_PURGE_INCOMING_ERROR_MSG_SPA 4045
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_SPA 4046
#define IDS_512BITS_SPA                 4047
#define IDS_1024BITS_SPA                4048
#define IDS_1536BITS_SPA                4049
#define IDS_2048BITS_SPA                4050
#define IDS_4096BITS_SPA                4051
#define IDS_KEY_GENERATION_SELECT_SIZE_SPA 4052
#define IDS_KEY_GENERATION_DLG_CAPTION_SPA 4053
#define IDS_GATHERING_RANDOMNESS_CAPTION_SPA 4054
#define IDS_GATHERING_RANDOMNESS_TEXT_SPA 4055
#define IDS_KEY_GENERATION_TIME_TEXT_SPA 4056
#define IDS_MUTE_CLOSE_MSG_CAPTION_SPA  4057
#define IDS_MUTE_CLOSE_MSG_TEXT_SPA     4058
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_SPA 4059
#define IDS_CONNECTIONS_COLHEADING_PORT_SPA 4060
#define IDS_CONNECTIONS_COLHEADING_SENT_SPA 4061
#define IDS_CONNECTIONS_COLHEADING_QUEUED_SPA 4062
#define IDS_CONNECTIONS_COLHEADING_DROPPED_SPA 4063
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_SPA 4064
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_SPA 4065
#define IDS_SEARCH_SEARCHING_STATUS_SPA 4066
#define IDS_SEARCH_IDLE_STATUS_SPA      4067
#define IDS_TOOLTIP_PURGE_HASH_FILES_SPA 4068
#define IDS_ADDED_TO_DLOADS_PREFIX_SPA  4069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_SPA 4070
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_SPA 4071
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_SPA 4072
#define IDS_SEARCH_BOOLEAN_AND_SPA      4073
#define IDS_SEARCH_BOOLEAN_OR_SPA       4074
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_SPA 4075
#define IDS_SEARCH_EXCLUDE_TEXT_SPA     4076
#define IDS_SEARCH_FILE_SIZE_LIMITS_SPA 4077
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_SPA 4078
#define IDS_SEARCH_BOOLEAN_ATLEAST_SPA  4079
#define IDS_SEARCH_BOOLEAN_ATMOST_SPA   4080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_SPA 4081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_SPA 4082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_SPA 4083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_SPA 4084
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_SPA 4085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_SPA 4086
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_SPA 4087
#define IDS_SEARCH_STOP_BUTTON_TEXT_SPA 4088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_SPA 4089
#define IDS_SEARCH_SEARCHFOR_TEXT_SPA   4090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_SPA 4091
#define IDS_COL_HEADING_FILENAME_SPA    4092
#define IDS_COL_HEADING_FILETYPE_SPA    4093
#define IDS_COL_HEADING_SIZE_SPA        4094
#define IDS_COL_HEADING_HASH_SPA        4095
#define IDS_COL_HEADING_HOST_VIP_SPA    4096
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_SPA 4097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_SPA 4098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_SPA 4099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_SPA 4100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_SPA 4101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_SPA 4102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_SPA 4103
#define IDS_DLOAD_CANCEL_BUTTON_SPA     4104
#define IDS_COL_HEADING_STATUS_SPA      4105
#define IDS_COL_HEADING_NUMRESUMES_SPA  4106
#define IDS_COL_HEADING_STARTTIME_SPA   4107
#define IDS_COL_HEADING_LASTUPDATETIME_SPA 4108
#define IDS_COL_HEADING_ROUTEQUALITY_SPA 4109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_SPA 4110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_SPA 4111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_SPA 4112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_SPA 4113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_SPA 4114
#define IDS_DLOAD_CANCELLED_SPA         4115
#define IDS_DLOAD_FETCHINGINFO_SPA      4116
#define IDS_DLOAD_RESUMING_SPA          4117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_SPA 4118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_SPA 4119
#define IDS_DLOAD_TIME_REMAINING_SPA    4120
#define IDS_ULOAD_BTN_REMOVALL_SPA      4121
#define IDS_ULOAD_BTN_CANCELCLEAR_SPA   4122
#define IDS_ULOAD_LIST_STARTINGUP_SPA   4123
#define IDS_ULOAD_STATUS_DONE_SPA       4124
#define IDS_ULOAD_STATUS_FAILED_SPA     4125
#define IDS_ULOAD_STATUS_STALLED_SPA    4126
#define IDS_ULOAD_TIMEREMAINING_SPA     4127
#define IDS_COL_HEADING_CHUNKSUPLOADED_SPA 4128
#define IDS_COL_HEADING_DESTINATION_VIP_SPA 4129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_SPA 4130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_SPA 4131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_SPA 4132
#define IDS_SETTINGS_INBOUND_LIMIT_SPA  4133
#define IDS_SETTINGS_OUTBOUND_LIMIT_SPA 4134
#define IDS_SETTINGS_MSG_SEC_LIMIT_SPA  4135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_SPA 4136
#define IDS_SETTINGS_DELETE_CANCELED_DL_SPA 4137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_SPA 4138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_SPA 4139
#define IDS_SETTINGS_CONNECTIONS_GROUP_SPA 4140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_SPA 4141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_SPA 4142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_SPA 4143
#define IDS_SETTINGS_MAX_UPLOADS_SPA    4144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_SPA 4145
#define IDS_BTN_BROWSE_SPA              4146
#define IDS_SETTINGS_SHAREFILESFROM_SPA 4147
#define IDS_SETTINGS_INCOMING_FOLDER_SPA 4148
#define IDS_SETTINGS_HASH_FOLDER_SPA    4149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_SPA 4150
#define IDS_SETTINGS_WEB_GROUP_SPA      4151
#define IDS_SETTINGS_ALLOW_ATMOST_SPA   4152
#define IDS_NO_SPA                      4153
#define IDS_YES_SPA                     4154
#define IDS_SETTINGS_LANGUAGE_GROUP_SPA 4155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_SPA 4156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_SPA 4157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_SPA 4158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_SPA 4159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_SPA 4160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_SPA 4161
#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_SPA 4162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_SPA 4163
#define IDS_DLOAD_QUEUE_SPA             4164
#define IDS_DLOAD_QUEUED_SPA            4165
#define IDS_DLOAD_QUEUED_SEARCHING_SPA  4166
#define IDS_MUTE_HELP_SPA               4167
#define IDS_MUTE_ABOUT_SPA              4168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_SPA 4169
#define IDS_REFRESH_BUTTON_TEXT_SPA     4170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_SPA 4171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_SPA 4172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_SPA 4173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_SPA 4174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_SPA 4175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_SPA 4176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_SPA 4177
#define IDS_NOTCONNECTED_SPA            4178
#define IDS_CONNECTED_SPA               4179
#define IDS_UUSERS_SPA                  4180
#define IDS_TRAFFIC_TEXT_SPA            4181
#define IDS_SEARCH_RESULTS_LBL_SPA      4182
#define IDS_UPDOWN_SPA                  4183
#define IDS_MUTENET_SPA                 4184
#define IDS_SEARCH_NORESULT_DAN         5001
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_DAN 5002
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_DAN 5003
#define IDS_KEY_LENGTH_WINDOW_TITLE_DAN 5004
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_DAN 5005
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_DAN 5006
#define IDS_CONNECTIONS_TAB_PORT_TEXT_DAN 5007
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_DAN 5008
#define IDS_CONNECTIONS_TAB_STARTUP_DAN 5009
#define IDS_DLOADS_TAB_PURGE_INCOMING_DAN 5010
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_DAN 5011
#define IDS_DLOADS_TAB_EXPLORE_SHARED_DAN 5012
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_DAN 5013
#define IDS_DLOADS_TAB_CLEAR_FAILED_DAN 5014
#define IDS_DLOADS_TAB_CANCEL_DAN       5015
#define IDS_TAB_TITLE_SEARCH_TEXT_DAN   5016
#define IDS_TAB_TITLE_DLOAD_TEXT_DAN    5017
#define IDS_TAB_TITLE_ULOAD_TEXT_DAN    5018
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_DAN 5019
#define IDS_TAB_TITLE_SETTINGS_TEXT_DAN 5020
#define IDS_TASK_TRAY_MENU_RESTORE_DAN  5021
#define IDS_TASK_TRAY_MENU_QUIT_DAN     5022
#define IDS_TRYING_TO_CONNECT_DAN       5023
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_DAN 5024
#define IDS_BEHIND_FIREWALL_QUESTION_DAN 5025
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_DAN 5026
#define IDS_TRACE_SAVING_RANDOMNESS_DAN 5027
#define IDS_TRACE_STOPPING_MSG_ROUTER_DAN 5028
#define IDS_TRACE_ALL_LAYERS_STOPPED_DAN 5029
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_DAN 5030
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_DAN 5031
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_DAN 5032
#define IDS_DLOAD_FAILED_DAN            5033
#define IDS_DLOAD_NOT_FOUND_DAN         5034
#define IDS_DLOAD_FILE_CORRUPTED_DAN    5035
#define IDS_DLOAD_CANCELLING_DAN        5036
#define IDS_DLOAD_COMPLETE_DAN          5037
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_DAN 5038
#define IDS_DLOAD_ATTEMPTING_RESUME_DAN 5039
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_DAN 5040
#define IDS_MUTE_ERROR_CAPTION_DAN      5041
#define IDS_PURGE_INCOMING_CAPTION_DAN  5042
#define IDS_PURGE_INCOMING_QUESTION_DAN 5043
#define IDS_PURGE_INCOMING_CAPTION_ERROR_DAN 5044
#define IDS_PURGE_INCOMING_ERROR_MSG_DAN 5045
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_DAN 5046
#define IDS_512BITS_DAN                 5047
#define IDS_1024BITS_DAN                5048
#define IDS_1536BITS_DAN                5049
#define IDS_2048BITS_DAN                5050
#define IDS_4096BITS_DAN                5051
#define IDS_KEY_GENERATION_SELECT_SIZE_DAN 5052
#define IDS_KEY_GENERATION_DLG_CAPTION_DAN 5053
#define IDS_GATHERING_RANDOMNESS_CAPTION_DAN 5054
#define IDS_GATHERING_RANDOMNESS_TEXT_DAN 5055
#define IDS_KEY_GENERATION_TIME_TEXT_DAN 5056
#define IDS_MUTE_CLOSE_MSG_CAPTION_DAN  5057
#define IDS_MUTE_CLOSE_MSG_TEXT_DAN     5058
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_DAN 5059
#define IDS_CONNECTIONS_COLHEADING_PORT_DAN 5060
#define IDS_CONNECTIONS_COLHEADING_SENT_DAN 5061
#define IDS_CONNECTIONS_COLHEADING_QUEUED_DAN 5062
#define IDS_CONNECTIONS_COLHEADING_DROPPED_DAN 5063
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_DAN 5064
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_DAN 5065
#define IDS_SEARCH_SEARCHING_STATUS_DAN 5066
#define IDS_SEARCH_IDLE_STATUS_DAN      5067
#define IDS_TOOLTIP_PURGE_HASH_FILES_DAN 5068
#define IDS_ADDED_TO_DLOADS_PREFIX_DAN  5069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_DAN 5070
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_DAN 5071
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_DAN 5072
#define IDS_SEARCH_BOOLEAN_AND_DAN      5073
#define IDS_SEARCH_BOOLEAN_OR_DAN       5074
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_DAN 5075
#define IDS_SEARCH_EXCLUDE_TEXT_DAN     5076
#define IDS_SEARCH_FILE_SIZE_LIMITS_DAN 5077
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_DAN 5078
#define IDS_SEARCH_BOOLEAN_ATLEAST_DAN  5079
#define IDS_SEARCH_BOOLEAN_ATMOST_DAN   5080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_DAN 5081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_DAN 5082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_DAN 5083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_DAN 5084
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_DAN 5085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_DAN 5086
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_DAN 5087
#define IDS_SEARCH_STOP_BUTTON_TEXT_DAN 5088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_DAN 5089
#define IDS_SEARCH_SEARCHFOR_TEXT_DAN   5090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_DAN 5091
#define IDS_COL_HEADING_FILENAME_DAN    5092
#define IDS_COL_HEADING_FILETYPE_DAN    5093
#define IDS_COL_HEADING_SIZE_DAN        5094
#define IDS_COL_HEADING_HASH_DAN        5095
#define IDS_COL_HEADING_HOST_VIP_DAN    5096
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_DAN 5097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_DAN 5098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_DAN 5099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_DAN 5100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_DAN 5101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_DAN 5102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_DAN 5103
#define IDS_DLOAD_CANCEL_BUTTON_DAN     5104
#define IDS_COL_HEADING_STATUS_DAN      5105
#define IDS_COL_HEADING_NUMRESUMES_DAN  5106
#define IDS_COL_HEADING_STARTTIME_DAN   5107
#define IDS_COL_HEADING_LASTUPDATETIME_DAN 5108
#define IDS_COL_HEADING_ROUTEQUALITY_DAN 5109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_DAN 5110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_DAN 5111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_DAN 5112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_DAN 5113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_DAN 5114
#define IDS_DLOAD_CANCELLED_DAN         5115
#define IDS_DLOAD_FETCHINGINFO_DAN      5116
#define IDS_DLOAD_RESUMING_DAN          5117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_DAN 5118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_DAN 5119
#define IDS_DLOAD_TIME_REMAINING_DAN    5120
#define IDS_ULOAD_BTN_REMOVALL_DAN      5121
#define IDS_ULOAD_BTN_CANCELCLEAR_DAN   5122
#define IDS_ULOAD_LIST_STARTINGUP_DAN   5123
#define IDS_ULOAD_STATUS_DONE_DAN       5124
#define IDS_ULOAD_STATUS_FAILED_DAN     5125
#define IDS_ULOAD_STATUS_STALLED_DAN    5126
#define IDS_ULOAD_TIMEREMAINING_DAN     5127
#define IDS_COL_HEADING_CHUNKSUPLOADED_DAN 5128
#define IDS_COL_HEADING_DESTINATION_VIP_DAN 5129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_DAN 5130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_DAN 5131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_DAN 5132
#define IDS_SETTINGS_INBOUND_LIMIT_DAN  5133
#define IDS_SETTINGS_OUTBOUND_LIMIT_DAN 5134
#define IDS_SETTINGS_MSG_SEC_LIMIT_DAN  5135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_DAN 5136
#define IDS_SETTINGS_DELETE_CANCELED_DL_DAN 5137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_DAN 5138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_DAN 5139
#define IDS_SETTINGS_CONNECTIONS_GROUP_DAN 5140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_DAN 5141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_DAN 5142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_DAN 5143
#define IDS_SETTINGS_MAX_UPLOADS_DAN    5144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_DAN 5145
#define IDS_BTN_BROWSE_DAN              5146
#define IDS_SETTINGS_SHAREFILESFROM_DAN 5147
#define IDS_SETTINGS_INCOMING_FOLDER_DAN 5148
#define IDS_SETTINGS_HASH_FOLDER_DAN    5149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_DAN 5150
#define IDS_SETTINGS_WEB_GROUP_DAN      5151
#define IDS_SETTINGS_ALLOW_ATMOST_DAN   5152
#define IDS_NO_DAN                      5153
#define IDS_YES_DAN                     5154
#define IDS_SETTINGS_LANGUAGE_GROUP_DAN 5155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_DAN 5156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_DAN 5157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_DAN 5158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_DAN 5159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_DAN 5160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_DAN 5161
#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_DAN 5162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_DAN 5163
#define IDS_DLOAD_QUEUE_DAN             5164
#define IDS_DLOAD_QUEUED_DAN            5165
#define IDS_DLOAD_QUEUED_SEARCHING_DAN  5166
#define IDS_MUTE_HELP_DAN               5167
#define IDS_MUTE_ABOUT_DAN              5168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_DAN 5169
#define IDS_REFRESH_BUTTON_TEXT_DAN     5170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_DAN 5171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_DAN 5172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_DAN 5173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_DAN 5174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_DAN 5175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_DAN 5176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_DAN 5177
#define IDS_NOTCONNECTED_DAN            5178
#define IDS_CONNECTED_DAN               5179
#define IDS_UUSERS_DAN                  5180
#define IDS_TRAFFIC_TEXT_DAN            5181
#define IDS_SEARCH_RESULTS_LBL_DAN      5182
#define IDS_UPDOWN_DAN                  5183
#define IDS_MUTENET_DAN                 5184
#define IDS_SEARCH_NORESULT_LITH        6001
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_LITH 6002
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_LITH 6003
#define IDS_KEY_LENGTH_WINDOW_TITLE_LITH 6004
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_LITH 6005
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_LITH 6006
#define IDS_CONNECTIONS_TAB_PORT_TEXT_LITH 6007
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_LITH 6008
#define IDS_CONNECTIONS_TAB_STARTUP_LITH 6009
#define IDS_DLOADS_TAB_PURGE_INCOMING_LITH 6010
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_LITH 6011
#define IDS_DLOADS_TAB_EXPLORE_SHARED_LITH 6012
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_LITH 6013
#define IDS_DLOADS_TAB_CLEAR_FAILED_LITH 6014
#define IDS_DLOADS_TAB_CANCEL_LITH      6015
#define IDS_TAB_TITLE_SEARCH_TEXT_LITH  6016
#define IDS_TAB_TITLE_DLOAD_TEXT_LITH   6017
#define IDS_TAB_TITLE_ULOAD_TEXT_LITH   6018
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_LITH 6019
#define IDS_TAB_TITLE_SETTINGS_TEXT_LITH 6020
#define IDS_TASK_TRAY_MENU_RESTORE_LITH 6021
#define IDS_TASK_TRAY_MENU_QUIT_LITH    6022
#define IDS_TRYING_TO_CONNECT_LITH      6023
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_LITH 6024
#define IDS_BEHIND_FIREWALL_QUESTION_LITH 6025
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_LITH 6026
#define IDS_TRACE_SAVING_RANDOMNESS_LITH 6027
#define IDS_TRACE_STOPPING_MSG_ROUTER_LITH 6028
#define IDS_TRACE_ALL_LAYERS_STOPPED_LITH 6029
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_LITH 6030
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_LITH 6031
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_LITH 6032
#define IDS_DLOAD_FAILED_LITH           6033
#define IDS_DLOAD_NOT_FOUND_LITH        6034
#define IDS_DLOAD_FILE_CORRUPTED_LITH   6035
#define IDS_DLOAD_CANCELLING_LITH       6036
#define IDS_DLOAD_COMPLETE_LITH         6037
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_LITH 6038
#define IDS_DLOAD_ATTEMPTING_RESUME_LITH 6039
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_LITH 6040
#define IDS_MUTE_ERROR_CAPTION_LITH     6041
#define IDS_PURGE_INCOMING_CAPTION_LITH 6042
#define IDS_PURGE_INCOMING_QUESTION_LITH 6043
#define IDS_PURGE_INCOMING_CAPTION_ERROR_LITH 6044
#define IDS_PURGE_INCOMING_ERROR_MSG_LITH 6045
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_LITH 6046
#define IDS_512BITS_LITH                6047
#define IDS_1024BITS_LITH               6048
#define IDS_1536BITS_LITH               6049
#define IDS_2048BITS_LITH               6050
#define IDS_4096BITS_LITH               6051
#define IDS_KEY_GENERATION_SELECT_SIZE_LITH 6052
#define IDS_KEY_GENERATION_DLG_CAPTION_LITH 6053
#define IDS_GATHERING_RANDOMNESS_CAPTION_LITH 6054
#define IDS_GATHERING_RANDOMNESS_TEXT_LITH 6055
#define IDS_KEY_GENERATION_TIME_TEXT_LITH 6056
#define IDS_MUTE_CLOSE_MSG_CAPTION_LITH 6057
#define IDS_MUTE_CLOSE_MSG_TEXT_LITH    6058
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_LITH 6059
#define IDS_CONNECTIONS_COLHEADING_PORT_LITH 6060
#define IDS_CONNECTIONS_COLHEADING_SENT_LITH 6061
#define IDS_CONNECTIONS_COLHEADING_QUEUED_LITH 6062
#define IDS_CONNECTIONS_COLHEADING_DROPPED_LITH 6063
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_LITH 6064
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_LITH 6065
#define IDS_SEARCH_SEARCHING_STATUS_LITH 6066
#define IDS_SEARCH_IDLE_STATUS_LITH     6067
#define IDS_TOOLTIP_PURGE_HASH_FILES_LITH 6068
#define IDS_ADDED_TO_DLOADS_PREFIX_LITH 6069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_LITH 6070
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_LITH 6071
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_LITH 6072
#define IDS_SEARCH_BOOLEAN_AND_LITH     6073
#define IDS_SEARCH_BOOLEAN_OR_LITH      6074
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_LITH 6075
#define IDS_SEARCH_EXCLUDE_TEXT_LITH    6076
#define IDS_SEARCH_FILE_SIZE_LIMITS_LITH 6077
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_LITH 6078
#define IDS_SEARCH_BOOLEAN_ATLEAST_LITH 6079
#define IDS_SEARCH_BOOLEAN_ATMOST_LITH  6080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_LITH 6081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_LITH 6082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_LITH 6083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_LITH 6084
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_LITH 6085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_LITH 6086
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_LITH 6087
#define IDS_SEARCH_STOP_BUTTON_TEXT_LITH 6088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_LITH 6089
#define IDS_SEARCH_SEARCHFOR_TEXT_LITH  6090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_LITH 6091
#define IDS_COL_HEADING_FILENAME_LITH   6092
#define IDS_COL_HEADING_FILETYPE_LITH   6093
#define IDS_COL_HEADING_SIZE_LITH       6094
#define IDS_COL_HEADING_HASH_LITH       6095
#define IDS_COL_HEADING_HOST_VIP_LITH   6096
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_LITH 6097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_LITH 6098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_LITH 6099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_LITH 6100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_LITH 6101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_LITH 6102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_LITH 6103
#define IDS_DLOAD_CANCEL_BUTTON_LITH    6104
#define IDS_COL_HEADING_STATUS_LITH     6105
#define IDS_COL_HEADING_NUMRESUMES_LITH 6106
#define IDS_COL_HEADING_STARTTIME_LITH  6107
#define IDS_COL_HEADING_LASTUPDATETIME_LITH 6108
#define IDS_COL_HEADING_ROUTEQUALITY_LITH 6109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_LITH 6110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_LITH 6111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_LITH 6112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_LITH 6113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_LITH 6114
#define IDS_DLOAD_CANCELLED_LITH        6115
#define IDS_DLOAD_FETCHINGINFO_LITH     6116
#define IDS_DLOAD_RESUMING_LITH         6117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_LITH 6118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_LITH 6119
#define IDS_DLOAD_TIME_REMAINING_LITH   6120
#define IDS_ULOAD_BTN_REMOVALL_LITH     6121
#define IDS_ULOAD_BTN_CANCELCLEAR_LITH  6122
#define IDS_ULOAD_LIST_STARTINGUP_LITH  6123
#define IDS_ULOAD_STATUS_DONE_LITH      6124
#define IDS_ULOAD_STATUS_FAILED_LITH    6125
#define IDS_ULOAD_STATUS_STALLED_LITH   6126
#define IDS_ULOAD_TIMEREMAINING_LITH    6127
#define IDS_COL_HEADING_CHUNKSUPLOADED_LITH 6128
#define IDS_COL_HEADING_DESTINATION_VIP_LITH 6129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_LITH 6130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_LITH 6131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_LITH 6132
#define IDS_SETTINGS_INBOUND_LIMIT_LITH 6133
#define IDS_SETTINGS_OUTBOUND_LIMIT_LITH 6134
#define IDS_SETTINGS_MSG_SEC_LIMIT_LITH 6135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_LITH 6136
#define IDS_SETTINGS_DELETE_CANCELED_DL_LITH 6137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_LITH 6138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_LITH 6139
#define IDS_SETTINGS_CONNECTIONS_GROUP_LITH 6140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_LITH 6141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_LITH 6142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_LITH 6143
#define IDS_SETTINGS_MAX_UPLOADS_LITH   6144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_LITH 6145
#define IDS_BTN_BROWSE_LITH             6146
#define IDS_SETTINGS_SHAREFILESFROM_LITH 6147
#define IDS_SETTINGS_INCOMING_FOLDER_LITH 6148
#define IDS_SETTINGS_HASH_FOLDER_LITH   6149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_LITH 6150
#define IDS_SETTINGS_WEB_GROUP_LITH     6151
#define IDS_SETTINGS_ALLOW_ATMOST_LITH  6152
#define IDS_NO_LITH                     6153
#define IDS_YES_LITH                    6154
#define IDS_SETTINGS_LANGUAGE_GROUP_LITH 6155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_LITH 6156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_LITH 6157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_LITH 6158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_LITH 6159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_LITH 6160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_LITH 6161
#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_LITH 6162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_LITH 6163
#define IDS_DLOAD_QUEUE_LITH            6164
#define IDS_DLOAD_QUEUED_LITH           6165
#define IDS_DLOAD_QUEUED_SEARCHING_LITH 6166
#define IDS_MUTE_HELP_LITH              6167
#define IDS_MUTE_ABOUT_LITH             6168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_LITH 6169
#define IDS_REFRESH_BUTTON_TEXT_LITH    6170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_LITH 6171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_LITH 6172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_LITH 6173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_LITH 6174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_LITH 6175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_LITH 6176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_LITH 6177
#define IDS_NOTCONNECTED_LITH           6178
#define IDS_CONNECTED_LITH              6179
#define IDS_UUSERS_LITH                 6180
#define IDS_TRAFFIC_TEXT_LITH           6181
#define IDS_SEARCH_RESULTS_LBL_LITH     6182
#define IDS_UPDOWN_LITH                 6183
#define IDS_MUTENET_LITH                6184
#define IDS_SEARCH_NORESULT_TURK        7001
#define IDS_GEN_KEY_PAIR_WINDOW_TITLE_TURK 7002
#define IDS_GEN_KEY_PAIR_WINDOW_MAIN_TEXT_TURK 7003
#define IDS_KEY_LENGTH_WINDOW_TITLE_TURK 7004
#define IDS_KEY_LENGTH_WINDOW_MAIN_TEXT_TURK 7005
#define IDS_CONNECTIONS_TAB_ADDRESS_TEXT_TURK 7006
#define IDS_CONNECTIONS_TAB_PORT_TEXT_TURK 7007
#define IDS_CONNECTIONS_TAB_ADDHOST_BTN_TEXT_TURK 7008
#define IDS_CONNECTIONS_TAB_STARTUP_TURK 7009
#define IDS_DLOADS_TAB_PURGE_INCOMING_TURK 7010
#define IDS_DLOADS_TAB_EXPLORE_INCOMING_TURK 7011
#define IDS_DLOADS_TAB_EXPLORE_SHARED_TURK 7012
#define IDS_DLOADS_TAB_CLEAR_COMPLETE_TURK 7013
#define IDS_DLOADS_TAB_CLEAR_FAILED_TURK 7014
#define IDS_DLOADS_TAB_CANCEL_TURK      7015
#define IDS_TAB_TITLE_SEARCH_TEXT_TURK  7016
#define IDS_TAB_TITLE_DLOAD_TEXT_TURK   7017
#define IDS_TAB_TITLE_ULOAD_TEXT_TURK   7018
#define IDS_TAB_TITLE_CONNECTIONS_TEXT_TURK 7019
#define IDS_TAB_TITLE_SETTINGS_TEXT_TURK 7020
#define IDS_TASK_TRAY_MENU_RESTORE_TURK 7021
#define IDS_TASK_TRAY_MENU_QUIT_TURK    7022
#define IDS_TRYING_TO_CONNECT_TURK      7023
#define IDS_BEHIND_FIREWALL_POPUP_CAPTION_TURK 7024
#define IDS_BEHIND_FIREWALL_QUESTION_TURK 7025
#define IDS_TRACE_STOPPING_FILE_SHARING_LAYER_TURK 7026
#define IDS_TRACE_SAVING_RANDOMNESS_TURK 7027
#define IDS_TRACE_STOPPING_MSG_ROUTER_TURK 7028
#define IDS_TRACE_ALL_LAYERS_STOPPED_TURK 7029
#define IDS_TOOLTIP_EXPLORE_SHARED_FILES_TURK 7030
#define IDS_TOOLTIP_EXPLORE_INCOMING_FILES_TURK 7031
#define IDS_TOOLTIP_PURGE_INCOMING_FILES_TURK 7032
#define IDS_DLOAD_FAILED_TURK           7033
#define IDS_DLOAD_NOT_FOUND_TURK        7034
#define IDS_DLOAD_FILE_CORRUPTED_TURK   7035
#define IDS_DLOAD_CANCELLING_TURK       7036
#define IDS_DLOAD_COMPLETE_TURK         7037
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_OF_TURK 7038
#define IDS_DLOAD_ATTEMPTING_RESUME_TURK 7039
#define IDS_SHARING_FOLDER_DOES_NOT_EXIST_TURK 7040
#define IDS_MUTE_ERROR_CAPTION_TURK     7041
#define IDS_PURGE_INCOMING_CAPTION_TURK 7042
#define IDS_PURGE_INCOMING_QUESTION_TURK 7043
#define IDS_PURGE_INCOMING_CAPTION_ERROR_TURK 7044
#define IDS_PURGE_INCOMING_ERROR_MSG_TURK 7045
#define IDS_INCOMING_FOLDER_DOES_NOT_EXIST_TURK 7046
#define IDS_512BITS_TURK                7047
#define IDS_1024BITS_TURK               7048
#define IDS_1536BITS_TURK               7049
#define IDS_2048BITS_TURK               7050
#define IDS_4096BITS_TURK               7051
#define IDS_KEY_GENERATION_SELECT_SIZE_TURK 7052
#define IDS_KEY_GENERATION_DLG_CAPTION_TURK 7053
#define IDS_GATHERING_RANDOMNESS_CAPTION_TURK 7054
#define IDS_GATHERING_RANDOMNESS_TEXT_TURK 7055
#define IDS_KEY_GENERATION_TIME_TEXT_TURK 7056
#define IDS_MUTE_CLOSE_MSG_CAPTION_TURK 7057
#define IDS_MUTE_CLOSE_MSG_TEXT_TURK    7058
#define IDS_CONNECTIONS_COLHEADING_ADDRESS_TURK 7059
#define IDS_CONNECTIONS_COLHEADING_PORT_TURK 7060
#define IDS_CONNECTIONS_COLHEADING_SENT_TURK 7061
#define IDS_CONNECTIONS_COLHEADING_QUEUED_TURK 7062
#define IDS_CONNECTIONS_COLHEADING_DROPPED_TURK 7063
#define IDS_ADDHOST_ERROR_MSGBOX_CAPTION_TURK 7064
#define IDS_ADDHOST_ERROR_MSGBOX_MSG_TURK 7065
#define IDS_SEARCH_SEARCHING_STATUS_TURK 7066
#define IDS_SEARCH_IDLE_STATUS_TURK     7067
#define IDS_TOOLTIP_PURGE_HASH_FILES_TURK 7068
#define IDS_ADDED_TO_DLOADS_PREFIX_TURK 7069
#define IDS_EXPORT_SEARCH_DLG_CAPTION_TURK 7070
#define IDS_SEARCH_EXPORT_SEARCH_TEXT_TAG_TURK 7071
#define IDS_SEARCH_EXPORT_SEARCH_BOOLEAN_TAG_TURK 7072
#define IDS_SEARCH_BOOLEAN_AND_TURK     7073
#define IDS_SEARCH_BOOLEAN_OR_TURK      7074
#define IDS_SEARCH_BOOLEAN_ENTIRE_PHRASE_TURK 7075
#define IDS_SEARCH_EXCLUDE_TEXT_TURK    7076
#define IDS_SEARCH_FILE_SIZE_LIMITS_TURK 7077
#define IDS_SEARCH_FILE_SIZE_BOOLEAN_TURK 7078
#define IDS_SEARCH_BOOLEAN_ATLEAST_TURK 7079
#define IDS_SEARCH_BOOLEAN_ATMOST_TURK  7080
#define IDS_SEARCH_EXPORT_FILE_COL_HEADINGS_TURK 7081
#define IDS_PURGE_HASHES_MSGBOX_CAPTION_TURK 7082
#define IDS_PURGE_HASHES_MSGBOX_TEXT_TURK 7083
#define IDS_SEARCH_EXPORT_BUTTON_TEXT_TURK 7084
#define IDS_SEARCH_DLOAD_BUTTON_TEXT_TURK 7085
#define IDS_SEARCH_CLEARRESULTS_BUTTON_TEXT_TURK 7086
#define IDS_SEARCH_SEARCH_BUTTON_TEXT_TURK 7087
#define IDS_SEARCH_STOP_BUTTON_TEXT_TURK 7088
#define IDS_SEARCH_PURGE_HASH_BUTTON_TEXT_TURK 7089
#define IDS_SEARCH_SEARCHFOR_TEXT_TURK  7090
#define IDS_SEARCH_SEARCHEXCLUDE_TEXT_TURK 7091
#define IDS_COL_HEADING_FILENAME_TURK   7092
#define IDS_COL_HEADING_FILETYPE_TURK   7093
#define IDS_COL_HEADING_SIZE_TURK       7094
#define IDS_COL_HEADING_HASH_TURK       7095
#define IDS_COL_HEADING_HOST_VIP_TURK   7096
#define IDS_SEARCH_RT_CLK_MENU_CAPTION_TURK 7097
#define IDS_SEARCH_RT_CLK_MENU_DLOAD_TURK 7098
#define IDS_DLOAD_EXPLORE_SHARED_BUTTON_TURK 7099
#define IDS_DLOAD_EXPLORE_INCOMING_BUTTON_TURK 7100
#define IDS_DLOAD_PURGE_INCOMING_BUTTON_TURK 7101
#define IDS_DLOAD_CLEAR_COMPLETE_BUTTON_TURK 7102
#define IDS_DLOAD_CLEAR_FAILED_BUTTON_TURK 7103
#define IDS_DLOAD_CANCEL_BUTTON_TURK    7104
#define IDS_COL_HEADING_STATUS_TURK     7105
#define IDS_COL_HEADING_NUMRESUMES_TURK 7106
#define IDS_COL_HEADING_STARTTIME_TURK  7107
#define IDS_COL_HEADING_LASTUPDATETIME_TURK 7108
#define IDS_COL_HEADING_ROUTEQUALITY_TURK 7109
#define IDS_DLOAD_RT_CLK_MENU_CAPTION_TURK 7110
#define IDS_DLOAD_RT_CLK_MENU_CANCEL_TURK 7111
#define IDS_DLOAD_RT_CLK_MENU_CLEAR_TURK 7112
#define IDS_DLOAD_RT_CLK_MENU_CLEARCOMPLETE_TURK 7113
#define IDS_DLOAD_RT_CLK_MENU_REMOVESTALLED_TURK 7114
#define IDS_DLOAD_CANCELLED_TURK        7115
#define IDS_DLOAD_FETCHINGINFO_TURK     7116
#define IDS_DLOAD_RESUMING_TURK         7117
#define IDS_DLOAD_ONE_HUNDRED_PERCENT_TURK 7118
#define IDS_DLOAD_FAILED_TO_WRITE_LOCAL_FILE_TURK 7119
#define IDS_DLOAD_TIME_REMAINING_TURK   7120
#define IDS_ULOAD_BTN_REMOVALL_TURK     7121
#define IDS_ULOAD_BTN_CANCELCLEAR_TURK  7122
#define IDS_ULOAD_LIST_STARTINGUP_TURK  7123
#define IDS_ULOAD_STATUS_DONE_TURK      7124
#define IDS_ULOAD_STATUS_FAILED_TURK    7125
#define IDS_ULOAD_STATUS_STALLED_TURK   7126
#define IDS_ULOAD_TIMEREMAINING_TURK    7127
#define IDS_COL_HEADING_CHUNKSUPLOADED_TURK 7128
#define IDS_COL_HEADING_DESTINATION_VIP_TURK 7129
#define IDS_ULOAD_RT_CLK_MENU_CAPTION_TURK 7130
#define IDS_ULOAD_RT_CLK_MENU_CANCEL_TURK 7131
#define IDS_ULOAD_RT_CLK_MENU_REMOVEALL_TURK 7132
#define IDS_SETTINGS_INBOUND_LIMIT_TURK 7133
#define IDS_SETTINGS_OUTBOUND_LIMIT_TURK 7134
#define IDS_SETTINGS_MSG_SEC_LIMIT_TURK 7135
#define IDS_SETTINGS_INITIAL_DL_TIMEOUT_TURK 7136
#define IDS_SETTINGS_DELETE_CANCELED_DL_TURK 7137
#define IDS_SETTINGS_MESSAGE_LIMIT_GROUP_TURK 7138
#define IDS_SETTINGS_DLOAD_SETTINGS_GROUP_TURK 7139
#define IDS_SETTINGS_CONNECTIONS_GROUP_TURK 7140
#define IDS_SETTINGS_MAINTAIN_ATLEAST_TURK 7141
#define IDS_SETTINGS_NEIGHBORCONNECTIONS_TURK 7142
#define IDS_SETTINGS_UPLOAD_CONTROLS_GROUP_TURK 7143
#define IDS_SETTINGS_MAX_UPLOADS_TURK   7144
#define IDS_SETTINGS_MAX_UPLOADS_PER_VIP_TURK 7145
#define IDS_BTN_BROWSE_TURK             7146
#define IDS_SETTINGS_SHAREFILESFROM_TURK 7147
#define IDS_SETTINGS_INCOMING_FOLDER_TURK 7148
#define IDS_SETTINGS_HASH_FOLDER_TURK   7149
#define IDS_SETTINGS_SAVE_SETTINGS_BTN_TURK 7150
#define IDS_SETTINGS_WEB_GROUP_TURK     7151
#define IDS_SETTINGS_ALLOW_ATMOST_TURK  7152
#define IDS_NO_TURK                     7153
#define IDS_YES_TURK                    7154
#define IDS_SETTINGS_LANGUAGE_GROUP_TURK 7155
#define IDS_BROWSE_SHARING_FOLDER_CAPTION_TURK 7156
#define IDS_BROWSE_INCOMING_FOLDER_CAPTION_TURK 7157
#define IDS_BROWSE_HASH_FOLDER_CAPTION_TURK 7158
#define IDS_MUTE_SHARE_FOLDER_DOESNT_EXIST_TURK 7159
#define IDS_MUTE_INCOMING_FOLDER_DOESNT_EXIST_TURK 7160
#define IDS_MUTE_HASH_FOLDER_DOESNT_EXIST_TURK 7161
#define IDS_SETTINGS_LANGUAGERESTART_MSG_CAPTION_TURK 7162
#define IDS_SETTINGS_LANGUAGERESTART_MSG_TEXT_TURK 7163
#define IDS_DLOAD_QUEUE_TURK            7164
#define IDS_DLOAD_QUEUED_TURK           7165
#define IDS_DLOAD_QUEUED_SEARCHING_TURK 7166
#define IDS_MUTE_HELP_TURK              7167
#define IDS_MUTE_ABOUT_TURK             7168
#define IDS_TAB_TITLE_SHAREDFILES_TEXT_TURK 7169
#define IDS_REFRESH_BUTTON_TEXT_TURK    7170
#define IDS_SHARED_FILES_EXPORT_BUTTON_TEXT_TURK 7171
#define IDS_SHARED_FILES_EXPORT_DLG_CAPTION_TEXT_TURK 7172
#define IDS_DLOAD_RT_CLK_MENU_SEARCH_QUEUE_ITEM_NEXT_TURK 7173
#define IDS_UPLOADS_UPLOADS_SHOWING_LABEL_TURK 7174
#define IDS_UPLOADS_TOTAL_CHUNKS_UPLOADED_LABEL_TURK 7175
#define IDS_SETTINGS_PORT_CHANGE_RESTART_TEXT_TURK 7176
#define IDS_SETTINGS_PORT_CHANGE_RESTART_CAPTION_TURK 7177
#define IDS_NOTCONNECTED_TURK           7178
#define IDS_CONNECTED_TURK              7179
#define IDS_UUSERS_TURK                 7180
#define IDS_TRAFFIC_TEXT_TURK           7181
#define IDS_SEARCH_RESULTS_LBL_TURK     7182
#define IDS_UPDOWN_TURK                 7183
#define IDS_MUTENET_TURK                7184

#endif // _MFC_MUTE_STRING_RESOURCES_H_

